tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: blended_skill_talk_therapy
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 200
opt:
  debug: True
  models:
    blender_1Bdistill:
      model: transformer/generator
      model_file: tmp/1Bdistill_model/1Bdistill_2.checkpoint # tmp/unl_app_1/unl_app_1 #
      interactive_mode: True
additional_args:
  page_id: 1 # Configure Your Own Page

